
name: Docs

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'CHANGES'
      - 'openvdb_maya/**'
      - 'pendingchanges/**'
      - '**.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'CHANGES'
      - 'openvdb_maya/**'
      - 'pendingchanges/**'
      - '**.md'
  workflow_dispatch:

jobs:
  doxygen:
    runs-on: ubuntu-latest
    env:
      CXX: g++
    container:
      image: aswf/ci-openvdb:2019
    steps:
    - uses: actions/checkout@v2
    - name: install_doxygen
      run: ./ci/install_doxygen.sh 1_8_11
    - name: install_epydoc
      run: pip install epydoc
    - name: install_latex
      run: yum -y install texlive-latex-bin texlive-dvips texlive-collection-fontsrecommended texlive-collection-latexrecommended
    - name: build
      run: ./ci/build.sh Release "core,python,doc" \
        -DUSE_BLOSC=OFF \
        -DOPENVDB_CORE_STATIC=OFF \
        -DOPENVDB_PYTHON_WRAP_ALL_GRID_TYPES=ON \
        -DDISABLE_DEPENDENCY_VERSION_CHECKS=ON
    - name: epydoc
      run: |
        epydoc --html -o /usr/local/share/doc/OpenVDB/html/python pyopenvdb
    - name: deploy
      # only deploy documentation to gh-pages on a manual workflow dispatch
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /usr/local/share/doc/OpenVDB/html
