
# This workflow is for running various sanitizers on OpenVDB. We currently
# only use clang over gcc (for no particular reason). Note that some of the
# errors produces by these sanitizers may be fairly obscure as the
# llvm-symbolizer is not installed on the openvdb image. The address
# sanitizer should never fail.

name: Sanitizers

on:
  schedule:
    # run this workflow on the 1st and 15th (i.e. twice a month) at 00:00 UTC
    - cron:  '0 0 1,15 * *'
  workflow_dispatch:

jobs:
  linux-sanitizers:
    runs-on: ubuntu-latest
    name: linux-clang-sanitizer:${{ matrix.config.build }}
    container:
      image: aswf/ci-openvdb:2021
    env:
      CXX: clang++
    strategy:
      matrix:
        config:
          - { build: 'asan',  cmake: '-DUSE_BLOSC=OFF' } # We never called blosc_destroy(), so disable blosc to silence these errors
          - { build: 'ubsan', cmake: '' } # Currently doesn't error, just reports all issues
          #- { build: 'lsan', cmake: '' } # asan encompasses and includes lsan
          #- { build: 'tsan', cmake: '' } # requires full stack rebuild for valid results (including libc++)
          #- { build: 'msan', cmake: '' } # requires full stack rebuild for valid results (including libc++)
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: install_gtest
      run: ./ci/install_gtest.sh 1.8.0
    - name: build
      run: ./ci/build.sh ${{ matrix.config.build }} None ON None "core,axcore,test,axtest" \
        -DOPENVDB_CXX_STRICT=ON -DOPENVDB_CORE_STATIC=OFF -DOPENVDB_AX_STATIC=OFF \
        -DCMAKE_VERBOSE_MAKEFILE=ON ${{ matrix.config.cmake }}
    - name: test
      run: cd build && ctest -V

  linux-gcov:
    runs-on: ubuntu-latest
    container:
      image: aswf/ci-openvdb:2021
    env:
      CXX: g++
    steps:
    - uses: actions/checkout@v2
    - name: install_gtest
      run: ./ci/install_gtest.sh 1.8.0
    - name: install_gcovr
      run: pip install gcovr
    - name: build
      run: ./ci/build.sh coverage None ON None "core,axcore,test,axtest" \
        -DOPENVDB_CORE_STATIC=OFF -DOPENVDB_AX_STATIC=OFF \
        -DCMAKE_VERBOSE_MAKEFILE=ON
    - name: test_and_gcov
      run: |
        cd build
        ctest -V
        make gcov_html
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/gcov_html
        destination_dir: code_coverage
        commit_message: "code coverage update"
